import pytest
import random
import os
from app.ml.inference import calculate_premium


def base_kwargs(**overrides):
    defaults = {
        "enrollment_week": 6,
        "flood_hazard_zone_tier": "medium",
        "zone_cluster_id": 5,
        "platform": "zomato",
        "season_flag": "NE_monsoon",
        "delivery_baseline_30d": 420.0,
        "income_baseline_weekly": 4000.0,
        "open_meteo_7d_precip_probability": 0.4,
        "activity_consistency_score": 0.8,
        "tenure_discount_factor": 1.0,
        "historical_claim_rate_zone": 0.1,
        "language": "tamil"
    }
    defaults.update(overrides)
    return defaults


def test_glm_used_for_week_3():
    result = calculate_premium(**base_kwargs(enrollment_week=3))
    assert result["model_used"] == "glm"


def test_lgbm_used_for_week_6():
    result = calculate_premium(**base_kwargs(enrollment_week=6))
    assert result["model_used"] == "lgbm"


def test_recency_multiplier_week_1():
    result = calculate_premium(**base_kwargs(enrollment_week=1))
    assert result["recency_multiplier"] == 1.5


def test_recency_multiplier_week_3():
    result = calculate_premium(**base_kwargs(enrollment_week=3))
    assert result["recency_multiplier"] == 1.25


def test_recency_multiplier_week_5():
    result = calculate_premium(**base_kwargs(enrollment_week=5))
    assert result["recency_multiplier"] == 1.0


def test_affordability_cap_applied():
    result = calculate_premium(**base_kwargs(income_baseline_weekly=1000.0))
    # cap = 1000 * 0.025 = 25.0, floor is 49.0, so final = 49.0
    assert result["affordability_capped"] is True
    assert result["premium_amount"] == 49.0


def test_premium_within_bounds_random():
    for _ in range(10):
        result = calculate_premium(**base_kwargs(
            enrollment_week=random.randint(1, 10),
            income_baseline_weekly=random.uniform(2000.0, 10000.0)
        ))
        assert 49.0 <= result["premium_amount"] <= 149.0


def test_shap_empty_for_glm():
    result = calculate_premium(**base_kwargs(enrollment_week=3))
    assert result["shap_top3"] == []


def test_shap_three_items_for_lgbm():
    result = calculate_premium(**base_kwargs(enrollment_week=6))
    assert len(result["shap_top3"]) == 3


def test_csv_data_validation():
    csv_path = "data/synthetic_training_data.csv"
    if not os.path.exists(csv_path):
        pytest.skip("CSV not yet generated by Person 2A")
    import pandas as pd
    df = pd.read_csv(csv_path)
    assert len(df) == 10000
    assert df["weekly_premium"].notnull().all()
    assert (df["weekly_premium"] >= 49.0).all()
    assert (df["weekly_premium"] <= 149.0).all()


def test_real_glm_loaded_if_artifacts_exist():
    """If glm_m1.joblib exists, model_used should be 'glm' not 'stub'"""
    import os
    artifact_path = os.path.join(os.path.dirname(__file__), "../../app/ml/artifacts/glm_m1.joblib")
    if not os.path.exists(artifact_path):
        pytest.skip("glm_m1.joblib not present")
    result = calculate_premium(**base_kwargs(enrollment_week=3))
    assert result["model_used"] == "glm"

def test_real_lgbm_loaded_if_artifacts_exist():
    """If lgbm_m2.joblib exists, model_used should be 'lgbm' not 'stub'"""
    import os
    artifact_path = os.path.join(os.path.dirname(__file__), "../../app/ml/artifacts/lgbm_m2.joblib")
    if not os.path.exists(artifact_path):
        pytest.skip("lgbm_m2.joblib not present")
    result = calculate_premium(**base_kwargs(enrollment_week=6))
    assert result["model_used"] == "lgbm"
    assert len(result["shap_top3"]) == 3
    for s in result["shap_top3"]:
        assert len(s) > 0
