import pytest
import random
import os
from pathlib import Path
import tempfile
import pandas as pd
import joblib
from app.ml.inference import calculate_premium
from scripts.synthetic_data import (
    DEFAULT_NUM_ROWS,
    WEEKLY_PREMIUM_CEILING,
    WEEKLY_PREMIUM_FLOOR,
    compute_weekly_premium_target,
    generate_synthetic_training_data,
    save_synthetic_training_data,
)
from scripts.train_premium_models import (
    load_training_data,
    train_m1_glm_cold_start,
    train_m2_lgbm_weekly,
)


# ---------------------------------------------------------------------------
# Section 2 — Helper
# ---------------------------------------------------------------------------

def base_kwargs(**overrides):
    defaults = {
        "enrollment_week": 6,
        "flood_hazard_zone_tier": "medium",
        "zone_cluster_id": 5,
        "platform": "zomato",
        "season_flag": "NE_monsoon",
        "delivery_baseline_30d": 420.0,
        "income_baseline_weekly": 4000.0,
        "open_meteo_7d_precip_probability": 0.4,
        "activity_consistency_score": 0.8,
        "tenure_discount_factor": 1.0,
        "historical_claim_rate_zone": 0.1,
        "language": "tamil"
    }
    defaults.update(overrides)
    return defaults


# ---------------------------------------------------------------------------
# Section 3 — Person 2B inference tests
# ---------------------------------------------------------------------------

def test_glm_used_for_week_3():
    result = calculate_premium(**base_kwargs(enrollment_week=3))
    assert result["model_used"] == "glm"


def test_lgbm_used_for_week_6():
    result = calculate_premium(**base_kwargs(enrollment_week=6))
    assert result["model_used"] == "lgbm"


def test_recency_multiplier_week_1():
    result = calculate_premium(**base_kwargs(enrollment_week=1))
    assert result["recency_multiplier"] == 1.5


def test_recency_multiplier_week_3():
    result = calculate_premium(**base_kwargs(enrollment_week=3))
    assert result["recency_multiplier"] == 1.25


def test_recency_multiplier_week_5():
    result = calculate_premium(**base_kwargs(enrollment_week=5))
    assert result["recency_multiplier"] == 1.0


def test_affordability_cap_applied():
    result = calculate_premium(**base_kwargs(income_baseline_weekly=1000.0))
    # cap = 1000 * 0.025 = 25.0, floor is 49.0, so final = 49.0
    assert result["affordability_capped"] is True
    assert result["premium_amount"] == 49.0


def test_premium_within_bounds_random():
    for _ in range(10):
        result = calculate_premium(**base_kwargs(
            enrollment_week=random.randint(1, 10),
            income_baseline_weekly=random.uniform(2000.0, 10000.0)
        ))
        assert 49.0 <= result["premium_amount"] <= 149.0


def test_shap_empty_for_glm():
    result = calculate_premium(**base_kwargs(enrollment_week=3))
    assert result["shap_top3"] == []


def test_shap_three_items_for_lgbm():
    result = calculate_premium(**base_kwargs(enrollment_week=6))
    assert len(result["shap_top3"]) == 3


def test_csv_data_validation():
    """Validate synthetic training CSV generated by Person 2A."""
    csv_path = os.path.join(os.path.dirname(__file__), "../../data/synthetic_training_data.csv")
    if not os.path.exists(csv_path):
        pytest.skip("CSV not yet generated by Person 2A")
    df = pd.read_csv(csv_path)
    assert len(df) == 10000, f"Expected 10000 rows, got {len(df)}"
    assert df["weekly_premium"].notna().all(), "Null values found in weekly_premium column"
    assert (df["weekly_premium"] >= 49.0).all(), "Some premiums below ₹49 floor"
    assert (df["weekly_premium"] <= 149.0).all(), "Some premiums above ₹149 ceiling"


def test_real_glm_loaded_if_artifacts_exist():
    """If glm_m1.joblib exists, model_used should be 'glm' not 'stub'"""
    artifact_path = os.path.join(os.path.dirname(__file__), "../../app/ml/artifacts/glm_m1.joblib")
    if not os.path.exists(artifact_path):
        pytest.skip("glm_m1.joblib not present")
    result = calculate_premium(**base_kwargs(enrollment_week=3))
    assert result["model_used"] == "glm"


def test_real_lgbm_loaded_if_artifacts_exist():
    """If lgbm_m2.joblib exists, model_used should be 'lgbm' not 'stub'"""
    artifact_path = os.path.join(os.path.dirname(__file__), "../../app/ml/artifacts/lgbm_m2.joblib")
    if not os.path.exists(artifact_path):
        pytest.skip("lgbm_m2.joblib not present")
    result = calculate_premium(**base_kwargs(enrollment_week=6))
    assert result["model_used"] == "lgbm"
    assert len(result["shap_top3"]) == 3
    for s in result["shap_top3"]:
        assert len(s) > 0


def test_m5_loaded_if_artifact_exists():
    """If kmeans_m5.joblib exists, get_zone_cluster_for_pincode_ml should return an int."""
    from app.ml.inference import get_zone_cluster_for_pincode_ml
    artifact_path = os.path.join(os.path.dirname(__file__), "../../app/ml/artifacts/kmeans_m5.joblib")
    if not os.path.exists(artifact_path):
        pytest.skip("kmeans_m5.joblib not present")
    result = get_zone_cluster_for_pincode_ml(13.0827, 80.2707)
    assert isinstance(result, int)


# ---------------------------------------------------------------------------
# Section 4 — Person 2A training / data test classes
# ---------------------------------------------------------------------------

class TestTrainPremiumModelsDataLoader:
    """Tests for CSV loading and schema validation in training pipeline."""

    def test_load_training_data_happy_path(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            csv_path = Path(temp_dir) / "training_premium.csv"
            pd.DataFrame(
                {
                    "flood_hazard_zone_tier": ["high"],
                    "season_flag": ["NE_monsoon"],
                    "platform": ["zomato"],
                    "zone_cluster_id": [1],
                    "delivery_baseline_30d": [300.0],
                    "income_baseline_weekly": [4000.0],
                    "enrollment_week": [6],
                    "open_meteo_7d_precip_probability": [0.7],
                    "activity_consistency_score": [0.8],
                    "tenure_discount_factor": [0.95],
                    "historical_claim_rate_zone": [0.2],
                    "zone_claim_match": [1],
                    "activity_7d_score": [1.0],
                    "claim_to_enrollment_days": [120],
                    "event_claim_frequency": [1],
                    "weekly_premium": [99.0],
                }
            ).to_csv(csv_path, index=False)

            loaded = load_training_data(csv_path)
            assert loaded.shape == (1, 16)

    def test_load_training_data_missing_columns_raises(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            csv_path = Path(temp_dir) / "training_premium.csv"
            pd.DataFrame({"platform": ["zomato"]}).to_csv(csv_path, index=False)

            with pytest.raises(ValueError) as error_info:
                load_training_data(csv_path)

            assert "missing required columns" in str(error_info.value)


class TestTrainM1GlmColdStart:
    """Tests for M1 cold-start GLM training."""

    def test_train_m1_glm_cold_start_saves_artifact_and_returns_metrics(self):
        rows = []
        for index in range(20):
            rows.append(
                {
                    "flood_hazard_zone_tier": "high" if index % 2 else "medium",
                    "season_flag": "NE_monsoon" if index % 3 else "SW_monsoon",
                    "platform": "zomato" if index % 2 else "swiggy",
                    "zone_cluster_id": 1,
                    "delivery_baseline_30d": 300.0,
                    "income_baseline_weekly": 4000.0,
                    "enrollment_week": (index % 4) + 1,
                    "open_meteo_7d_precip_probability": 0.65,
                    "activity_consistency_score": 0.75,
                    "tenure_discount_factor": 0.95,
                    "historical_claim_rate_zone": 0.20,
                    "zone_claim_match": 1,
                    "activity_7d_score": 1.0,
                    "claim_to_enrollment_days": 120,
                    "event_claim_frequency": 1,
                    "weekly_premium": 80.0 + (index % 5),
                }
            )

        frame = pd.DataFrame(rows)

        with tempfile.TemporaryDirectory() as temp_dir:
            artifact_path = Path(temp_dir) / "glm_cold_start.joblib"
            result = train_m1_glm_cold_start(frame, artifact_path)

            assert artifact_path.exists()
            assert result["rmse"] >= 0.0
            assert result["train_rows"] > 0
            assert result["valid_rows"] > 0

            artifact = joblib.load(artifact_path)
            assert artifact["model_name"] == "glm_cold_start"
            assert set(artifact["features"]) == {"flood_hazard_zone_tier", "season_flag", "platform"}
            assert set(artifact["encoders"].keys()) == {"flood_hazard_zone_tier", "season_flag", "platform"}

    def test_train_m1_glm_cold_start_raises_when_no_week_1_to_4_rows(self):
        frame = pd.DataFrame(
            {
                "flood_hazard_zone_tier": ["high", "low"],
                "season_flag": ["NE_monsoon", "heat"],
                "platform": ["zomato", "swiggy"],
                "enrollment_week": [5, 10],
                "weekly_premium": [99.0, 105.0],
                "zone_claim_match": [1, 1],
                "activity_7d_score": [1.0, 1.1],
                "claim_to_enrollment_days": [120, 180],
                "event_claim_frequency": [1, 1],
                "zone_cluster_id": [1, 2],
                "delivery_baseline_30d": [260.0, 280.0],
                "income_baseline_weekly": [3600.0, 4200.0],
                "open_meteo_7d_precip_probability": [0.5, 0.6],
                "activity_consistency_score": [0.7, 0.8],
                "tenure_discount_factor": [0.95, 0.90],
                "historical_claim_rate_zone": [0.2, 0.3],
            }
        )

        with tempfile.TemporaryDirectory() as temp_dir:
            artifact_path = Path(temp_dir) / "glm_cold_start.joblib"
            with pytest.raises(ValueError) as error_info:
                train_m1_glm_cold_start(frame, artifact_path)

            assert "enrollment_week < 5" in str(error_info.value)


class TestTrainM2LgbmWeekly:
    """Tests for M2 LightGBM weekly premium training."""

    def test_train_m2_lgbm_weekly_saves_all_artifacts(self):
        rows = []
        for index in range(60):
            rows.append(
                {
                    "flood_hazard_zone_tier": ["low", "medium", "high"][index % 3],
                    "season_flag": ["dry_season", "heat", "SW_monsoon", "NE_monsoon"][index % 4],
                    "platform": "zomato" if index % 2 else "swiggy",
                    "zone_cluster_id": (index % 20) + 1,
                    "delivery_baseline_30d": 180.0 + float(index),
                    "income_baseline_weekly": 2500.0 + float(index * 20),
                    "enrollment_week": 5 + (index % 20),
                    "open_meteo_7d_precip_probability": 0.20 + (index % 10) * 0.05,
                    "activity_consistency_score": 0.30 + (index % 7) * 0.08,
                    "tenure_discount_factor": 0.85 + (index % 10) * 0.01,
                    "historical_claim_rate_zone": 0.05 + (index % 12) * 0.02,
                    "zone_claim_match": 1,
                    "activity_7d_score": 0.9,
                    "claim_to_enrollment_days": 100,
                    "event_claim_frequency": 1,
                    "weekly_premium": 49.0 + (index % 60),
                }
            )

        frame = pd.DataFrame(rows)

        with tempfile.TemporaryDirectory() as temp_dir:
            model_path = Path(temp_dir) / "lgbm_m2.joblib"
            shap_path = Path(temp_dir) / "shap_explainer_m2.joblib"
            feature_path = Path(temp_dir) / "lgbm_m2_feature_list.joblib"

            result = train_m2_lgbm_weekly(frame, model_path, shap_path, feature_path)

            assert model_path.exists()
            assert shap_path.exists()
            assert feature_path.exists()
            assert result["rmse"] >= 0.0
            assert result["train_rows"] > 0
            assert result["valid_rows"] > 0
            assert result["negative_predictions"] == 0

            model = joblib.load(model_path)
            feature_list = joblib.load(feature_path)
            assert model.objective == "tweedie"
            assert model.tweedie_variance_power == 1.5
            assert len(feature_list) == 11

    def test_train_m2_lgbm_weekly_raises_when_no_week_5_plus_rows(self):
        frame = pd.DataFrame(
            {
                "flood_hazard_zone_tier": ["high", "low"],
                "season_flag": ["NE_monsoon", "heat"],
                "platform": ["zomato", "swiggy"],
                "zone_cluster_id": [1, 2],
                "delivery_baseline_30d": [250.0, 260.0],
                "income_baseline_weekly": [3500.0, 3600.0],
                "enrollment_week": [2, 4],
                "open_meteo_7d_precip_probability": [0.7, 0.4],
                "activity_consistency_score": [0.8, 0.6],
                "tenure_discount_factor": [0.95, 0.96],
                "historical_claim_rate_zone": [0.2, 0.1],
                "zone_claim_match": [1, 1],
                "activity_7d_score": [1.0, 1.0],
                "claim_to_enrollment_days": [120, 90],
                "event_claim_frequency": [1, 2],
                "weekly_premium": [90.0, 85.0],
            }
        )

        with tempfile.TemporaryDirectory() as temp_dir:
            model_path = Path(temp_dir) / "lgbm_m2.joblib"
            shap_path = Path(temp_dir) / "shap_explainer_m2.joblib"
            feature_path = Path(temp_dir) / "lgbm_m2_feature_list.joblib"

            with pytest.raises(ValueError) as error_info:
                train_m2_lgbm_weekly(frame, model_path, shap_path, feature_path)

            assert "enrollment_week >= 5" in str(error_info.value)


class TestComputeWeeklyPremiumTarget:
    """Tests for premium target computation from loss ratio simulation."""

    def test_low_tier_dry_season_at_floor(self):
        """Low flood tier + dry season should hit ₹49 floor."""
        premium = compute_weekly_premium_target(
            avg_heavy_rain_days_yr=30.0,
            flood_tier_numeric=1,
            season="dry_season",
        )
        # Base: 174 * 1.0 (low tier) = 174
        # Adjusted: 174 * 1.1 (climate) = 191.4
        # Annual: 191.4 / 0.65 = 294.46
        # Weekly: (294.46 / 52) * 0.8 (dry) = 4.55 -> clamped to 49
        assert abs(premium - 49.0) <= 0.01

    def test_high_tier_ne_monsoon_near_ceiling(self):
        """High flood tier + NE monsoon should remain within configured bounds."""
        premium = compute_weekly_premium_target(
            avg_heavy_rain_days_yr=80.0,
            flood_tier_numeric=3,
            season="NE_monsoon",
        )
        assert WEEKLY_PREMIUM_FLOOR <= premium <= WEEKLY_PREMIUM_CEILING

    def test_medium_tier_heat_season(self):
        """Medium flood tier + heat season produces mid-range premium."""
        premium = compute_weekly_premium_target(
            avg_heavy_rain_days_yr=50.0,
            flood_tier_numeric=2,
            season="heat",
        )
        # Base: 174 * 1.5 (medium tier) = 261
        # Adjusted: 261 * 1.1 (climate) = 287.1
        # Annual: 287.1 / 0.65 = 441.69
        # Weekly: (441.69 / 52) * 1.1 (heat) = 9.35
        assert WEEKLY_PREMIUM_FLOOR <= premium <= WEEKLY_PREMIUM_CEILING

    def test_invalid_flood_tier_raises(self):
        """Invalid flood_tier_numeric should raise ValueError."""
        try:
            compute_weekly_premium_target(
                avg_heavy_rain_days_yr=50.0,
                flood_tier_numeric=4,
                season="dry_season",
            )
        except ValueError as error:
            assert "flood_tier_numeric must be 1, 2, or 3" in str(error)
        else:
            raise AssertionError("Expected ValueError")

    def test_invalid_season_raises(self):
        """Invalid season should raise ValueError."""
        try:
            compute_weekly_premium_target(
                avg_heavy_rain_days_yr=50.0,
                flood_tier_numeric=2,
                season="invalid_season",
            )
        except ValueError as error:
            assert "season must be one of" in str(error)
        else:
            raise AssertionError("Expected ValueError")

    def test_all_seasons_low_tier(self):
        """Verify season premiums are monotonic when clipping is taken into account."""
        premiums = {}
        for season in ["NE_monsoon", "SW_monsoon", "heat", "dry_season"]:
            premiums[season] = compute_weekly_premium_target(
                avg_heavy_rain_days_yr=40.0,
                flood_tier_numeric=1,
                season=season,
            )

        # With floor clipping, equal values are valid when raw premiums fall below floor.
        assert premiums["NE_monsoon"] >= premiums["SW_monsoon"]
        assert premiums["SW_monsoon"] >= premiums["heat"]
        assert premiums["heat"] >= premiums["dry_season"]

    def test_output_is_float_in_valid_range(self):
        """Output should always be float and within [49, 149]."""
        for flood_tier in [1, 2, 3]:
            for season in ["NE_monsoon", "SW_monsoon", "heat", "dry_season"]:
                premium = compute_weekly_premium_target(
                    avg_heavy_rain_days_yr=50.0,
                    flood_tier_numeric=flood_tier,
                    season=season,
                )
                assert isinstance(premium, float)
                assert 49.0 <= premium <= 149.0


class TestSyntheticTrainingData:
    """Tests for the synthetic CSV generation output."""

    def test_generate_synthetic_training_data_shape_and_columns(self):
        frame = generate_synthetic_training_data(num_rows=DEFAULT_NUM_ROWS, seed=42)

        expected_columns = [
            "flood_hazard_zone_tier",
            "zone_cluster_id",
            "platform",
            "delivery_baseline_30d",
            "income_baseline_weekly",
            "enrollment_week",
            "season_flag",
            "open_meteo_7d_precip_probability",
            "activity_consistency_score",
            "tenure_discount_factor",
            "historical_claim_rate_zone",
            "weekly_premium",
        ]

        assert frame.shape == (DEFAULT_NUM_ROWS, len(expected_columns))
        assert list(frame.columns) == expected_columns
        assert frame["weekly_premium"].between(WEEKLY_PREMIUM_FLOOR, WEEKLY_PREMIUM_CEILING).all()
        assert frame.isnull().sum().sum() == 0

    def test_save_synthetic_training_data_writes_csv(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            output_path = Path(temp_dir) / "synthetic_training_data.csv"
            frame = save_synthetic_training_data(output_path=output_path, num_rows=25, seed=42)

            assert output_path.exists()
            loaded = pd.read_csv(output_path)
            assert loaded.shape == frame.shape
            assert loaded.shape[0] == 25
